export const browserCoreExamples = [
  "secureclaw browser status",
  "secureclaw browser start",
  "secureclaw browser stop",
  "secureclaw browser tabs",
  "secureclaw browser open https://example.com",
  "secureclaw browser focus abcd1234",
  "secureclaw browser close abcd1234",
  "secureclaw browser screenshot",
  "secureclaw browser screenshot --full-page",
  "secureclaw browser screenshot --ref 12",
  "secureclaw browser snapshot",
  "secureclaw browser snapshot --format aria --limit 200",
  "secureclaw browser snapshot --efficient",
  "secureclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "secureclaw browser navigate https://example.com",
  "secureclaw browser resize 1280 720",
  "secureclaw browser click 12 --double",
  'secureclaw browser type 23 "hello" --submit',
  "secureclaw browser press Enter",
  "secureclaw browser hover 44",
  "secureclaw browser drag 10 11",
  "secureclaw browser select 9 OptionA OptionB",
  "secureclaw browser upload /tmp/file.pdf",
  'secureclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "secureclaw browser dialog --accept",
  'secureclaw browser wait --text "Done"',
  "secureclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "secureclaw browser console --level error",
  "secureclaw browser pdf",
];
