// NOTE: Now sourced from unified config. Import from config/defaults.unified.ts instead.
import { BROWSER_DEFAULTS } from "../config/defaults.unified.js";

export const DEFAULT_SECURECLAW_BROWSER_ENABLED = BROWSER_DEFAULTS.ENABLED;
export const DEFAULT_BROWSER_EVALUATE_ENABLED = BROWSER_DEFAULTS.EVALUATE_ENABLED;
export const DEFAULT_SECURECLAW_BROWSER_COLOR = BROWSER_DEFAULTS.COLOR;
export const DEFAULT_SECURECLAW_BROWSER_PROFILE_NAME = BROWSER_DEFAULTS.PROFILE_NAME;
export const DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = BROWSER_DEFAULTS.DEFAULT_PROFILE_NAME;
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS = BROWSER_DEFAULTS.AI_SNAPSHOT_MAX_CHARS;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS =
  BROWSER_DEFAULTS.AI_SNAPSHOT_EFFICIENT_MAX_CHARS;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = BROWSER_DEFAULTS.AI_SNAPSHOT_EFFICIENT_DEPTH;
