// ---------------------------------------------------------------------------
// IOC Seed Data -- Known-bad Indicators of Compromise
// ---------------------------------------------------------------------------
// Contains safe example entries for malicious domains, IPs, hashes, and URL
// patterns. All domains use reserved TLDs (.example.com, .example.net,
// .example.org, .test) per RFC 2606. All IPs use documentation ranges per
// RFC 5737 (192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24).
//
// Categories:
//   c2          -- Command and control infrastructure
//   phishing    -- Credential harvesting / login spoofs
//   malware     -- Malware distribution / payload hosting
//   cryptominer -- Cryptocurrency mining pools / droppers
//   data_exfil  -- Data exfiltration endpoints
// ---------------------------------------------------------------------------

import type { IOCEntry } from "./ioc-database.js";

let _counter = 0;
function nextId(): string {
  return `seed-${String(++_counter).padStart(4, "0")}`;
}

const now = new Date();

// ---------------------------------------------------------------------------
// Malicious Domains (~50)
// ---------------------------------------------------------------------------

export const SEED_DOMAINS: IOCEntry[] = [
  // -- C2 domains --
  {
    id: nextId(),
    type: "domain",
    value: "c2-server.example.net",
    category: "c2",
    severity: "critical",
    description: "Known Cobalt Strike C2 infrastructure",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "c2-beacon.example.com",
    category: "c2",
    severity: "critical",
    description: "Beacon callback domain for APT group",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "command-relay.example.org",
    category: "c2",
    severity: "critical",
    description: "C2 relay node for botnet operations",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "implant-callback.example.net",
    category: "c2",
    severity: "critical",
    description: "RAT implant callback endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "darkc2-panel.example.com",
    category: "c2",
    severity: "critical",
    description: "Dark C2 panel hosting domain",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "rat-controller.example.net",
    category: "c2",
    severity: "critical",
    description: "Remote access trojan controller",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "botnet-master.example.org",
    category: "c2",
    severity: "critical",
    description: "Botnet master control server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "dns-tunnel-c2.example.com",
    category: "c2",
    severity: "high",
    description: "DNS tunneling C2 channel",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "covert-channel.example.net",
    category: "c2",
    severity: "high",
    description: "Covert C2 communication channel",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "exfil-relay.example.org",
    category: "c2",
    severity: "high",
    description: "C2 exfiltration relay point",
    addedAt: now,
    source: "seed",
  },

  // -- Phishing domains --
  {
    id: nextId(),
    type: "domain",
    value: "secure-login-verify.example.com",
    category: "phishing",
    severity: "high",
    description: "Credential phishing site mimicking login portal",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "account-verify-now.example.net",
    category: "phishing",
    severity: "high",
    description: "Account verification phishing lure",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "password-reset-urgent.example.com",
    category: "phishing",
    severity: "high",
    description: "Fake password reset page",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "oauth-consent-page.example.org",
    category: "phishing",
    severity: "high",
    description: "Fake OAuth consent page for token theft",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "helpdesk-ticket-update.example.com",
    category: "phishing",
    severity: "medium",
    description: "Fake helpdesk ticket notification",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "invoice-payment-due.example.net",
    category: "phishing",
    severity: "high",
    description: "Business email compromise invoice phishing",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "shared-document-view.example.com",
    category: "phishing",
    severity: "medium",
    description: "Fake shared document credential harvester",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "mail-security-alert.example.org",
    category: "phishing",
    severity: "high",
    description: "Fake email security alert phishing",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "2fa-verify-token.example.com",
    category: "phishing",
    severity: "critical",
    description: "2FA token interception phishing",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "corporate-vpn-login.example.net",
    category: "phishing",
    severity: "high",
    description: "Fake corporate VPN login page",
    addedAt: now,
    source: "seed",
  },

  // -- Malware distribution domains --
  {
    id: nextId(),
    type: "domain",
    value: "evil-payload.example.com",
    category: "malware",
    severity: "critical",
    description: "Malware payload distribution server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "dropper-stage1.example.net",
    category: "malware",
    severity: "critical",
    description: "First-stage malware dropper",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "trojan-update.example.com",
    category: "malware",
    severity: "critical",
    description: "Trojan update/download server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "ransomware-key-server.example.org",
    category: "malware",
    severity: "critical",
    description: "Ransomware encryption key server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "exploit-kit-landing.example.com",
    category: "malware",
    severity: "critical",
    description: "Exploit kit landing page",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "malicious-update-cdn.example.net",
    category: "malware",
    severity: "high",
    description: "Fake software update CDN",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "drive-by-download.example.com",
    category: "malware",
    severity: "critical",
    description: "Drive-by download attack host",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "backdoor-installer.example.org",
    category: "malware",
    severity: "critical",
    description: "Backdoor installer distribution",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "infostealer-drop.example.net",
    category: "malware",
    severity: "high",
    description: "Information stealer malware drop site",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "worm-propagation.example.com",
    category: "malware",
    severity: "high",
    description: "Worm propagation and update server",
    addedAt: now,
    source: "seed",
  },

  // -- Cryptominer domains --
  {
    id: nextId(),
    type: "domain",
    value: "coinhive-proxy.example.com",
    category: "cryptominer",
    severity: "high",
    description: "Coinhive-style browser mining proxy",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "xmr-pool-proxy.example.net",
    category: "cryptominer",
    severity: "high",
    description: "Monero mining pool proxy",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "crypto-dropper.example.org",
    category: "cryptominer",
    severity: "high",
    description: "Cryptominer dropper distribution",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "mining-stratum-relay.example.com",
    category: "cryptominer",
    severity: "medium",
    description: "Stratum mining relay endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "stealth-miner-cdn.example.net",
    category: "cryptominer",
    severity: "high",
    description: "Stealth cryptominer CDN distribution",
    addedAt: now,
    source: "seed",
  },

  // -- Data exfiltration domains --
  {
    id: nextId(),
    type: "domain",
    value: "data-dump-receiver.example.com",
    category: "data_exfil",
    severity: "critical",
    description: "Exfiltrated data collection endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "paste-exfil.example.net",
    category: "data_exfil",
    severity: "high",
    description: "Paste-based data exfiltration service",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "dns-exfil-tunnel.example.org",
    category: "data_exfil",
    severity: "high",
    description: "DNS-based exfiltration tunnel endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "steganography-upload.example.com",
    category: "data_exfil",
    severity: "high",
    description: "Steganography-based data exfil upload",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "credential-log-drop.example.net",
    category: "data_exfil",
    severity: "critical",
    description: "Stolen credential drop site",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "keylogger-upload.example.com",
    category: "data_exfil",
    severity: "critical",
    description: "Keylogger data upload endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "screen-capture-exfil.example.org",
    category: "data_exfil",
    severity: "high",
    description: "Screen capture exfiltration endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "cloud-token-stealer.example.net",
    category: "data_exfil",
    severity: "critical",
    description: "Cloud token theft and exfil endpoint",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "browser-cookie-dump.example.com",
    category: "data_exfil",
    severity: "high",
    description: "Browser cookie exfiltration site",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "clipboard-stealer.example.org",
    category: "data_exfil",
    severity: "high",
    description: "Clipboard data exfiltration service",
    addedAt: now,
    source: "seed",
  },

  // -- Additional mixed domains to reach ~50 --
  {
    id: nextId(),
    type: "domain",
    value: "zero-day-exploit.example.com",
    category: "malware",
    severity: "critical",
    description: "Zero-day exploit distribution server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "spear-phish-docs.example.net",
    category: "phishing",
    severity: "high",
    description: "Spear phishing document host",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "supply-chain-poison.example.com",
    category: "malware",
    severity: "critical",
    description: "Supply chain poisoning package host",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "watering-hole-inject.example.org",
    category: "malware",
    severity: "high",
    description: "Watering hole attack injection server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "domain",
    value: "fake-captcha-loader.example.com",
    category: "phishing",
    severity: "medium",
    description: "Fake CAPTCHA malware loader",
    addedAt: now,
    source: "seed",
  },
];

// ---------------------------------------------------------------------------
// Malicious IP Ranges (~20, using RFC 5737 documentation ranges)
// ---------------------------------------------------------------------------

export const SEED_IPS: IOCEntry[] = [
  // -- 192.0.2.0/24 (TEST-NET-1) --
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.1",
    category: "c2",
    severity: "critical",
    description: "C2 server primary node",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.10",
    category: "c2",
    severity: "critical",
    description: "C2 beacon relay server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.50",
    category: "malware",
    severity: "critical",
    description: "Malware payload distribution server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.100",
    category: "phishing",
    severity: "high",
    description: "Phishing site hosting server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.200",
    category: "data_exfil",
    severity: "critical",
    description: "Data exfiltration collection point",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.0/24",
    category: "c2",
    severity: "high",
    description: "C2 infrastructure CIDR range (TEST-NET-1)",
    addedAt: now,
    source: "seed",
  },

  // -- 198.51.100.0/24 (TEST-NET-2) --
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.1",
    category: "malware",
    severity: "critical",
    description: "Ransomware key exchange server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.25",
    category: "cryptominer",
    severity: "high",
    description: "Illicit mining pool proxy",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.50",
    category: "phishing",
    severity: "high",
    description: "Phishing infrastructure node",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.100",
    category: "data_exfil",
    severity: "high",
    description: "Exfiltration staging server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.150",
    category: "c2",
    severity: "critical",
    description: "Fast-flux C2 node",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.0/24",
    category: "malware",
    severity: "high",
    description: "Malware infrastructure CIDR range (TEST-NET-2)",
    addedAt: now,
    source: "seed",
  },

  // -- 203.0.113.0/24 (TEST-NET-3) --
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.1",
    category: "c2",
    severity: "critical",
    description: "APT C2 primary controller",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.42",
    category: "malware",
    severity: "high",
    description: "Exploit kit hosting server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.66",
    category: "cryptominer",
    severity: "high",
    description: "Cryptojacking pool relay",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.100",
    category: "phishing",
    severity: "high",
    description: "Credential harvesting server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.200",
    category: "data_exfil",
    severity: "critical",
    description: "Stolen data collection server",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "203.0.113.0/24",
    category: "data_exfil",
    severity: "high",
    description: "Exfiltration infrastructure CIDR range (TEST-NET-3)",
    addedAt: now,
    source: "seed",
  },

  // -- Additional specific IPs --
  {
    id: nextId(),
    type: "ip",
    value: "192.0.2.222",
    category: "cryptominer",
    severity: "high",
    description: "Covert mining pool proxy",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "ip",
    value: "198.51.100.254",
    category: "c2",
    severity: "critical",
    description: "Backup C2 fallback node",
    addedAt: now,
    source: "seed",
  },
];

// ---------------------------------------------------------------------------
// Malicious File Hashes (example SHA-256, fabricated but plausible)
// ---------------------------------------------------------------------------

export const SEED_HASHES: IOCEntry[] = [
  {
    id: nextId(),
    type: "hash",
    value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    category: "malware",
    severity: "medium",
    description: "Empty file hash (often used as canary in malware checks)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "hash",
    value: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    category: "malware",
    severity: "critical",
    description: "Known ransomware payload hash (WannaCry-like sample)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "hash",
    value: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    category: "malware",
    severity: "critical",
    description: "Known trojan dropper binary",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "hash",
    value: "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe",
    category: "cryptominer",
    severity: "high",
    description: "Known XMRig cryptominer binary",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "hash",
    value: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    category: "c2",
    severity: "critical",
    description: "Cobalt Strike beacon payload",
    addedAt: now,
    source: "seed",
  },
];

// ---------------------------------------------------------------------------
// Malicious URL Patterns (~10 regex patterns)
// ---------------------------------------------------------------------------

export const SEED_URL_PATTERNS: IOCEntry[] = [
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]*login[^/]*\\.[^/]+/.*\\?(user|email|account)=",
    category: "phishing",
    severity: "high",
    description: "Credential phishing URL with login keyword and query parameter harvesting",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value:
      "https?://\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}[:/].*\\.(exe|msi|bat|cmd|ps1|vbs|scr)",
    category: "malware",
    severity: "critical",
    description: "Executable download from raw IP address (drive-by download)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]+/.*\\.(exe|msi|bat|cmd|ps1|vbs|scr|dll|hta)\\?[^\\s]*token=",
    category: "malware",
    severity: "high",
    description: "Executable download with suspicious token parameter",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]*password[^/]*reset[^/]*/.*\\?.*redirect",
    category: "phishing",
    severity: "high",
    description: "Fake password reset with redirect (credential interception)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]+/wp-(content|admin|includes)/.*\\.(php|js)\\?",
    category: "malware",
    severity: "medium",
    description: "Compromised WordPress site malware injection",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]*\\.tk/|https?://[^/]*\\.ml/|https?://[^/]*\\.ga/|https?://[^/]*\\.cf/",
    category: "phishing",
    severity: "medium",
    description: "Free TLD commonly abused for phishing (.tk, .ml, .ga, .cf)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]+/[^\\s]*base64[^\\s]*\\.(php|asp|jsp)",
    category: "malware",
    severity: "high",
    description: "Server-side script with base64 parameter (webshell indicator)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]+/\\.env|https?://[^/]+/config\\.json|https?://[^/]+/\\.git/",
    category: "data_exfil",
    severity: "high",
    description: "Sensitive file access attempt (.env, config, .git exposure)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]+@[^/]+/",
    category: "phishing",
    severity: "high",
    description: "URL with embedded credentials (basic auth phishing)",
    addedAt: now,
    source: "seed",
  },
  {
    id: nextId(),
    type: "url_pattern",
    value: "https?://[^/]*oauth[^/]*\\.[^/]+/.*\\?.*client_id=.*&redirect_uri=http:",
    category: "phishing",
    severity: "critical",
    description: "OAuth token theft via insecure redirect URI",
    addedAt: now,
    source: "seed",
  },
];

// ---------------------------------------------------------------------------
// All seed data combined
// ---------------------------------------------------------------------------

export const ALL_SEED_IOCS: IOCEntry[] = [
  ...SEED_DOMAINS,
  ...SEED_IPS,
  ...SEED_HASHES,
  ...SEED_URL_PATTERNS,
];
